global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ddarp-nodes'
    static_configs:
      - targets:
        - '172.20.0.10:8000'  # node1
        - '172.20.0.11:8000'  # node2
        - '172.20.0.12:8000'  # border1
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s